# Generated by Django 3.1.3 on 2020-12-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='upload')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='upload')),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
                ('facebook', models.CharField(blank=True, max_length=300)),
                ('google', models.CharField(blank=True, max_length=300)),
                ('twitter', models.CharField(blank=True, max_length=300)),
                ('skype', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='upload')),
                ('last_name', models.CharField(max_length=300)),
                ('first_name', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Glavniy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini1_description', models.CharField(blank=True, max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('mini2_description', models.CharField(blank=True, max_length=300)),
                ('mini3_description', models.CharField(blank=True, max_length=300)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('short_description1', models.CharField(blank=True, max_length=300)),
                ('short_description2', models.CharField(blank=True, max_length=300)),
                ('short_description3', models.CharField(blank=True, max_length=300)),
                ('short_description4', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Latest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_description', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='upload')),
                ('data', models.DateField()),
                ('comment', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='upload')),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('mini_description', models.CharField(max_length=300)),
                ('status', models.IntegerField(default=0)),
                ('short_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('email', models.EmailField(blank=True, max_length=300)),
                ('data', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='upload')),
                ('last_name', models.CharField(max_length=300)),
                ('first_name', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=300)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Success',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_description', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('first_name', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=300)),
                ('rating', models.IntegerField(default=0)),
                ('logo_left', models.ImageField(upload_to='upload')),
                ('logo_right', models.ImageField(upload_to='upload')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_description', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='upload')),
                ('short_description', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('first_name', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=300)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='upload')),
                ('title', models.CharField(max_length=300)),
                ('mini_description', models.CharField(max_length=300)),
            ],
        ),
    ]
