# Generated by Django 3.1.3 on 2020-12-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glavniy',
            old_name='mini1_description',
            new_name='mini_description1',
        ),
        migrations.RenameField(
            model_name='glavniy',
            old_name='mini2_description',
            new_name='mini_description2',
        ),
        migrations.RenameField(
            model_name='glavniy',
            old_name='mini3_description',
            new_name='mini_description3',
        ),
    ]
