# Generated by Django 3.1.3 on 2020-12-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201212_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faq',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='glavniy',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='information',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='latest',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opening',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partner',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='success',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tip',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
