# Generated by Django 3.1.3 on 2020-12-13 14:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_glavniy_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glavniy',
            name='mini_description3',
        ),
        migrations.AddField(
            model_name='glavniy',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
