# Generated by Django 3.1.3 on 2020-12-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201214_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='rating',
            new_name='status',
        ),
    ]
