# Generated by Django 3.1.3 on 2020-12-14 06:22

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201214_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='color',
            field=colorfield.fields.ColorField(default='', max_length=18),
        ),
    ]
