# Generated by Django 3.1.3 on 2020-12-14 06:23

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201214_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='', max_length=18),
        ),
    ]
