# Generated by Django 3.1.3 on 2020-12-14 06:28

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201214_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
