# Generated by Django 3.1.3 on 2020-12-14 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201214_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='color',
        ),
    ]
