# Generated by Django 3.1.3 on 2020-12-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_tip_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='logo',
        ),
        migrations.AddField(
            model_name='tip',
            name='logo_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
