# Generated by Django 3.1.3 on 2020-12-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201214_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='status',
        ),
    ]
