# Generated by Django 3.1.3 on 2020-12-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_tip_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='status',
        ),
        migrations.AddField(
            model_name='certificate',
            name='logo_in',
            field=models.ImageField(default='default logo_in', upload_to='upload'),
            preserve_default=False,
        ),
    ]
