# Generated by Django 3.1.3 on 2020-12-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201214_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
