# Generated by Django 3.1.3 on 2020-12-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_tip_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='facebook',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='doctor',
            name='skype',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='doctor',
            name='twitter',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
