# Generated by Django 3.1.3 on 2020-12-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201214_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
