# Generated by Django 3.1.3 on 2020-12-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_doctor_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
