# Generated by Django 3.1.3 on 2020-12-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_prize_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='data',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='register',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
