# Generated by Django 3.1.3 on 2020-12-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20201216_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
