# Generated by Django 3.1.3 on 2020-12-18 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201218_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='description',
        ),
    ]
