# Generated by Django 3.1.3 on 2020-12-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_information_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='short_description1',
            new_name='number_description',
        ),
    ]
