# Generated by Django 3.1.3 on 2020-12-18 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20201218_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prize',
            old_name='rating',
            new_name='number',
        ),
    ]
