# Generated by Django 3.1.3 on 2020-12-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20201218_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prize',
            name='mini_description',
        ),
        migrations.AddField(
            model_name='prize',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
