# Generated by Django 3.1.3 on 2020-12-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_prize_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='success',
            name='mini_description',
        ),
        migrations.AddField(
            model_name='success',
            name='description',
            field=models.TextField(default='default description'),
            preserve_default=False,
        ),
    ]
