# Generated by Django 3.1.3 on 2020-12-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_success_mini_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='success',
            name='job_1',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='success',
            name='job_2',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
