# Generated by Django 3.1.3 on 2020-12-19 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20201218_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='short_description3',
            new_name='testimonial_description',
        ),
    ]
