# Generated by Django 3.1.3 on 2020-12-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20201219_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='success',
            name='mini_logo',
            field=models.ImageField(default='default mini_logo', upload_to='upload'),
            preserve_default=False,
        ),
    ]
