# Generated by Django 3.1.3 on 2020-12-19 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_test_mini_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='mini_description',
        ),
    ]
