# Generated by Django 3.1.3 on 2020-12-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_test_mini_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(default='default description'),
            preserve_default=False,
        ),
    ]
