# Generated by Django 3.1.3 on 2020-12-19 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_test_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='short_description',
        ),
    ]
