# Generated by Django 3.1.3 on 2020-12-19 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_test_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='short_description4',
            new_name='latest_description',
        ),
    ]
