# Generated by Django 3.1.3 on 2020-12-19 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20201219_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latest',
            name='mini_description',
        ),
    ]
