# Generated by Django 3.1.3 on 2020-12-19 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_latest_mini_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latest',
            old_name='name',
            new_name='name_author',
        ),
    ]
