# Generated by Django 3.1.3 on 2020-12-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20201219_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='mini_description',
            field=models.CharField(default='default mini_description', max_length=300),
            preserve_default=False,
        ),
    ]
