# Generated by Django 3.1.3 on 2020-12-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_staff_mini_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_ssylka',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='opening',
            name='time_before',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opening',
            name='time_from',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='faq',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='description',
            field=models.TextField(),
        ),
    ]
