# Generated by Django 3.1.3 on 2020-12-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20201224_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opening',
            name='description',
        ),
        migrations.AlterField(
            model_name='opening',
            name='time_before',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='opening',
            name='time_from',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
