# Generated by Django 3.1.3 on 2020-12-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20201225_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='mini_description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
