# Generated by Django 3.1.3 on 2020-12-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_opening_mini_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('mini_description', models.CharField(blank=True, max_length=300)),
                ('data', models.DateField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
