# Generated by Django 3.1.3 on 2020-12-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='mini_description',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
