# Generated by Django 3.1.3 on 2020-12-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20201225_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='info_description',
            field=models.CharField(default='default info_description', max_length=300),
            preserve_default=False,
        ),
    ]
