# Generated by Django 3.1.3 on 2020-12-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_doctor_info_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='info_description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
