# Generated by Django 3.1.3 on 2020-12-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20201226_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='mini_description',
            field=models.CharField(default='default mini_description', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='quote_1',
            field=models.CharField(default='default quote_1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='quote_2',
            field=models.CharField(default='default quote_2', max_length=200),
            preserve_default=False,
        ),
    ]
