# Generated by Django 3.1.3 on 2020-12-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_about_quote_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glavniy',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
