# Generated by Django 3.1.3 on 2020-12-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20201226_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glavniy',
            name='description',
            field=models.TextField(blank=True, max_length=165),
        ),
    ]
