# Generated by Django 3.1.3 on 2020-12-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_history_history_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('description_1', models.CharField(blank=True, max_length=300)),
                ('description_2', models.CharField(blank=True, max_length=300)),
                ('description_3', models.CharField(blank=True, max_length=300)),
                ('description_4', models.CharField(blank=True, max_length=300)),
                ('youtube', models.CharField(blank=True, max_length=300)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
