# Generated by Django 3.1.3 on 2020-12-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_why_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='why_about',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
