# Generated by Django 3.1.3 on 2020-12-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_why_about_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='make_about_description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
