# Generated by Django 3.1.3 on 2020-12-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20201228_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
