# Generated by Django 3.1.3 on 2020-12-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_auto_20201228_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='make_about_description',
            new_name='about_mini_description',
        ),
    ]
