# Generated by Django 3.1.3 on 2020-12-30 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_history_history_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='history_title',
        ),
    ]
