# Generated by Django 3.1.3 on 2020-12-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_remove_history_history_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='service_mini_description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
