# Generated by Django 3.1.3 on 2020-12-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_information_service_mini_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='service_item_description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
