# Generated by Django 3.1.3 on 2020-12-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_auto_20201230_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='service_title_description',
            field=models.TextField(blank=True),
        ),
    ]
