# Generated by Django 3.1.3 on 2020-12-31 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_tip_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description_1', models.CharField(max_length=300)),
                ('description_2', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='upload')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.projecttype')),
            ],
        ),
    ]
