# Generated by Django 3.1.3 on 2021-01-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_auto_20201231_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='dc_mini_description',
            field=models.TextField(blank=True),
        ),
    ]
