# Generated by Django 3.1.3 on 2021-01-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_information_dc_mini_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors_all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('description_1', models.TextField(blank=True)),
                ('mini_1', models.CharField(max_length=300)),
                ('mini_2', models.CharField(max_length=300)),
                ('mini_3', models.CharField(max_length=300)),
                ('description_2', models.TextField(blank=True)),
                ('description_3', models.TextField(blank=True)),
                ('logo', models.ImageField(upload_to='upload')),
                ('mini_description', models.TextField()),
                ('last_name', models.CharField(blank=True, max_length=300)),
                ('first_name', models.CharField(blank=True, max_length=300)),
                ('position', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
