# Generated by Django 3.1.3 on 2021-01-05 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_doctors_all'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctors_all',
            new_name='Doctor_all',
        ),
    ]
