# Generated by Django 3.1.3 on 2021-01-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_auto_20210105_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='con_mini_description',
            field=models.TextField(blank=True),
        ),
    ]
