# Generated by Django 3.1.3 on 2021-01-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_information_con_mini_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marshrut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('icon', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
