# Generated by Django 3.1.3 on 2021-01-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_marshrut'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='make_about_description',
            field=models.TextField(blank=True),
        ),
    ]
