# Generated by Django 3.1.3 on 2021-01-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_information_make_about_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='make_about_description',
            new_name='make_mini_description',
        ),
    ]
