# Generated by Django 3.1.3 on 2021-01-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_conform'),
    ]

    operations = [
        migrations.AddField(
            model_name='conform',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
