# Generated by Django 3.1.3 on 2021-01-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_conform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='latest_mini_description',
            field=models.TextField(blank=True),
        ),
    ]
