# Generated by Django 3.1.3 on 2021-01-06 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_information_latest_mini_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='upload')),
                ('data', models.DateField()),
                ('comment', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=300)),
                ('name_author', models.CharField(max_length=300)),
                ('description_1', models.CharField(max_length=300)),
                ('description_2', models.CharField(max_length=300)),
                ('rating', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
