# Generated by Django 3.1.3 on 2021-01-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description_2',
            field=models.TextField(blank=True),
        ),
    ]
