# Generated by Django 3.1.3 on 2021-01-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_auto_20210106_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description_1',
            field=models.TextField(),
        ),
    ]
