# Generated by Django 3.1.3 on 2021-01-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_auto_20210106_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='useful_mini_description',
            field=models.TextField(blank=True),
        ),
    ]
