# Generated by Django 3.1.3 on 2021-01-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_information_useful_mini_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='useful_description',
            field=models.TextField(blank=True),
        ),
    ]
