# Generated by Django 3.1.3 on 2021-01-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_information_useful_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Useful',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_before', models.ImageField(upload_to='upload')),
                ('logo_after', models.ImageField(upload_to='upload')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('rating', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
