# Generated by Django 3.1.3 on 2021-01-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_useful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='info_description',
            field=models.TextField(blank=True),
        ),
    ]
