# Generated by Django 3.1.3 on 2021-01-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_auto_20210115_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='selectww',
            field=models.CharField(default='default selectww', max_length=300),
            preserve_default=False,
        ),
    ]
